<?php

use Myth\Controllers\ThemedController;

/**
 * Airports Controller
 *
 * Auto-generated by Sprint on 2020-11-16 20:58pm
 */
class Airports extends ThemedController {

    /**
     * The type of caching to use. The default values are
     * set globally in the environment's start file, but
     * these will override if they are set.
     */
    protected $cache_type      = null;
    protected $backup_cache    = null;

    // If set, this language file will automatically be loaded.
    protected $language_file   = null;

    // If set, this model file will automatically be loaded.
    protected $model_file      = 'Airport_model';

    
    /**
     * Allows per-controller override of theme.
     * @var null
     */
    protected $theme = null;

    /**
     * Per-controller override of the current layout file.
     * @var null
     */
    protected $layout = null;

    /**
     * The UIKit to make available to the template views.
     * @var string
     */
    protected $uikit = '';

    /**
     * The number of rows to show when paginating results.
     * @var int
     */
    protected $limit = 25;


    //--------------------------------------------------------------------

    public function __construct($skip=false)
    {
        // normal
        // if skip is true left with empty constructor so 
        // no iherited constructors will be called
        // For info, a missing constructor means inherited constructors
        // will be called
        if ($skip === false) {
            parent::__construct();
        }
    }

    // ------------------------------------------------------------------
    /**
     * The default method called. Typically displays an overview of this
     * controller's domain.
     *
     * @return mixed
     */
    public function index()
    {
        //Use $CI instaed of $this so that this controller can be callled from another controller
        $CI =& get_instance();      // the current controller instance

        $CI->load->library('table');
//        $CI->load->model('Airport_model');

        $CI->load->helper('url');

        $offset = $CI->uri->segment( $CI->uri->total_segments() );
//        $offset = $CI->uri->segment( $CI->uri->total_segments() );

//        $rows = $CI->airports/models/airport_model->limit($CI->limit, $offset)
//        $rows = $CI->airport_model->limit($CI->limit, $offset)
//                     ->as_array()
//                     ->find_all();
		$rows = $CI->Airport_model->as_array()
									->find_all();
        $CI->setVar('rows', $rows);

		$CI->render();
    }

    //--------------------------------------------------------------------

    /**
     * Create a single item.
     *
     * @return mixed
     */
    public function create()
    {
        $this->load->helper('form');
        $this->load->helper('inflector');
//        $this->load->model('Airport_model');    //load some other way

        if ($this->input->method() == 'post')
        {
            $post_data = $this->input->post();

//            if ($this->airports/models/airport_model->insert($post_data) )
            if ($this->Airport_model->insert($post_data) )
            {
                $this->setMessage('Successfully created item.', 'success');
                redirect( site_url('airports') );
            }

//            $this->setMessage('Error creating item. '. $this->airports/models/airport_model->error(), 'danger');
            $this->setMessage('Error creating item. '. $this->airport_model->error(), 'danger');
        }

		$this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Displays a single item.
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function show($id)
    {
//        $item = $this->airports/models/airport_model->find($id);
        $item = $this->airport_model->find($id);

        if (! $item)
        {
            $this->setMessage('Unable to find that item.', 'warning');
            redirect( site_url('airports') );
        }

        $this->setVar('item', $item);

		$this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Updates a single item.
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function update($id)
    {
        $this->load->helper('form');
        $this->load->helper('inflector');

        if ($this->input->method() == 'post')
        {
            $post_data = $this->input->post();

//            if ($this->airports/models/airport_model->update($id, $post_data))
            if ($this->Airport_model->update($id, $post_data))
            {
                $this->setMessage('Successfully updated item.', 'success');
                redirect( site_url('airports') );
            }

//            $this->setMessage('Error updating item. '. $this->airports/models/airport_model->error(), 'danger');
            $this->setMessage('Error updating item. '. $this->airport_model->error(), 'danger');
        }

//        $item = $this->airports/models/airport_model->find($id);
        $item = $this->Airport_model->find($id);
        $this->setVar('item', $item);

		$this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Deletes a single item
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function delete($id)
    {
//        if ($this->airports/models/airport_model->delete($id))
        if ($this->Airport_model->delete($id))
        {
            $this->setMessage('Successfully deleted item.', 'success');
            redirect( site_url('airports') );
        }

//        $this->setMessage('Error deleting item. '. $this->airports/models/airport_model->error(), 'danger');
        $this->setMessage('Error deleting item. '. $this->airport_model->error(), 'danger');
        redirect( site_url( 'airports' ) );
		
    }

    //--------------------------------------------------------------------

    /**
     * method to test HMVC controller to controller
     * Module::mycows::cows::testHMVC calls Module::Airports::airportTestHMVC (this)
     */
    public function airportTestHMVC()
    {
        $CI =& get_instance();      // the current controller instance (Eg: mycows::cows)

        $CI->load->helper('url');

        $offset = $CI->uri->segment( $CI->uri->total_segments() );
        $rows = $CI->Airport_model->as_array()
                                    ->find_all();

        return $rows;
    }
}
