<?php

use Myth\Controllers\ThemedController;

/**
 * Newmod Controller
 *
 * Auto-generated by Sprint on 2020-11-17 21:08pm
 */
class Newmod extends ThemedController {

    /**
     * The type of caching to use. The default values are
     * set globally in the environment's start file, but
     * these will override if they are set.
     */
    protected $cache_type      = null;
    protected $backup_cache    = null;

    // If set, this language file will automatically be loaded.
    protected $language_file   = null;

    // If set, this model file will automatically be loaded.
    protected $model_file      = null;

    
    /**
     * Allows per-controller override of theme.
     * @var null
     */
    protected $theme = null;

    /**
     * Per-controller override of the current layout file.
     * @var null
     */
    protected $layout = null;

    /**
     * The UIKit to make available to the template views.
     * @var string
     */
    protected $uikit = '';

    /**
     * The number of rows to show when paginating results.
     * @var int
     */
    protected $limit = 25;


    //--------------------------------------------------------------------

    /**
     * The default method called. Typically displays an overview of this
     * controller's domain.
     *
     * @return mixed
     */
    public function index()
    {
        $this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Create a single item.
     *
     * @return mixed
     */
    public function create()
    {
        $this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Displays a single item.
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function show($id)
    {
        $this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Updates a single item.
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function update($id)
    {
        $this->render();
    }

    //--------------------------------------------------------------------

    /**
     * Deletes a single item
     *
     * @param  int $id  The primary_key of the object.
     * @return mixed
     */
    public function delete($id)
    {
        
    }

    //--------------------------------------------------------------------
}
